spring:
  application:
    name: ${APPLICATION_NAME:service-query}
  profiles:
    active: prod
---
spring:
  jackson:
    default-property-inclusion: NON_NULL

server:
  port: ${APPLICATION_PORT:8090}
  compression:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: false