spring:
  application:
    name: ${APPLICATION_NAME:service-query}
server:
  port: ${APPLICATION_PORT:8090}
  compression:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: false