# Use root/example as user/password credentials

version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=pos
      - POSTGRES_PASSWORD=pos
    ports:
      - '5432:5432'
    volumes:
      - D:\target\posgrestdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8089:8080


