spring:
  application:
    name: ${APPLICATION_NAME:service-training}
  profiles:
    active: prod
---
spring:
  jackson:
    default-property-inclusion: NON_NULL
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresSQLDialect
    open-in-view: false
  datasource:
    url: jdbc:postgres://localhost:5432/score?useSSL=false
    username: postgres
    password: postgres
  config:
    activate:
      on-profile: prod
  sql:
    init:
      mode: always

server:
  port: ${APPLICATION_PORT:8080}
  compression:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: false