version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres

    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgresqldata:/var/lib/mysql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - backend


  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8088:8080
    networks:
      - backend
    depends_on:
      - db

volumes:
  postgresqldata:
networks:
  backend: